# Generated by Django 2.2.27 on 2022-03-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleColours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.TextField()),
                ('room', models.TextField()),
                ('element', models.TextField()),
                ('mirc_colour', models.TextField()),
            ],
            options={
                'db_table': 'bible_colours',
            },
        ),
        migrations.CreateModel(
            name='BibleDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strongs', models.CharField(db_index=True, max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'bible_dict',
            },
        ),
        migrations.CreateModel(
            name='BibleTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'bible_translations',
            },
        ),
        migrations.CreateModel(
            name='XRefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_book', models.CharField(max_length=15)),
                ('primary_chapter', models.IntegerField()),
                ('primary_verse', models.IntegerField()),
                ('xref_book1', models.CharField(max_length=15)),
                ('xref_chapter1', models.IntegerField()),
                ('xref_verse1', models.IntegerField()),
                ('xref_book2', models.CharField(blank=True, max_length=15, null=True)),
                ('xref_chapter2', models.IntegerField(blank=True, null=True)),
                ('xref_verse2', models.IntegerField(blank=True, null=True)),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'xrefs',
            },
        ),
        migrations.CreateModel(
            name='BibleStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_idx', models.IntegerField()),
                ('word', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
            ],
            options={
                'index_together': {('trans_idx', 'count')},
            },
        ),
        migrations.CreateModel(
            name='BibleBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_idx', models.IntegerField()),
                ('long_book_name', models.TextField()),
                ('canonical', models.TextField(blank=True)),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibleapp.BibleTranslations')),
            ],
            options={
                'db_table': 'bible_books',
            },
        ),
        migrations.CreateModel(
            name='BibleVerses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('verse_text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibleapp.BibleBooks')),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibleapp.BibleTranslations')),
            ],
            options={
                'db_table': 'bible_verses',
                'index_together': {('trans', 'book', 'chapter', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='BibleConcordance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('word_id', models.IntegerField()),
                ('word', models.CharField(max_length=60)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibleapp.BibleBooks')),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibleapp.BibleTranslations')),
            ],
            options={
                'db_table': 'bible_concordance',
                'index_together': {('trans', 'word', 'chapter'), ('trans', 'word'), ('trans', 'book', 'chapter', 'verse', 'word_id'), ('trans', 'word', 'chapter', 'verse')},
            },
        ),
    ]
