# Generated by Django 2.2.19 on 2021-04-06 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotsRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('rpc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.TextField(unique=True)),
            ],
            options={
                'permissions': (('bot_admin', 'Create user logins and assign permissions'), ('activate_plugins', 'Can activate/deactivate plugins network wide'), ('join_or_part_room', 'Join or part bot to rooms'), ('irc_cmd', 'Issue arbitrary command to bot'), ('set_pvt_version', 'Set bible version default in private chat window'), ('change_pvt_trigger', 'Set trigger used in private chat window'), ('change_nick', 'Can issue a bot nick change command'), ('warn_user', 'Warn a user of their behaviour')),
            },
        ),
        migrations.CreateModel(
            name='NetworkPlugins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.TextField()),
                ('loaded', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=15)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=40)),
                ('option_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('system', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.TextField()),
                ('room', models.TextField()),
                ('option', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_options',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=250)),
                ('option', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPlugins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logos.NetworkPlugins')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.TextField()),
                ('room', models.TextField()),
            ],
            options={
                'permissions': (('room_admin', 'Assign permissions to existing users of own room'), ('change_trigger', 'Change trigger'), ('set_default_translation', 'Set default room translation'), ('set_verse_limits', 'Set room verse limits'), ('set_greeting', 'Set room greeting message'), ('can_speak', 'Speak through bot'), ('enable_plugins', 'Can enable or disable room plugins'), ('kick_user', 'Can kick user'), ('ban_user', 'Can ban user'), ('room_op', 'Bot can op'), ('twitter_op', 'Can add or remove twitter follows')),
                'unique_together': {('network', 'room')},
            },
        ),
        migrations.AddField(
            model_name='networkplugins',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logos.Plugins'),
        ),
    ]
