# Generated by Django 2.2.19 on 2021-04-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotsRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('rpc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OptionLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=15)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=40)),
                ('option_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RoomOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.TextField()),
                ('room', models.TextField()),
                ('option', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_options',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
