# Generated by Django 2.2.19 on 2021-04-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkPermissions',
        ),
        migrations.RemoveField(
            model_name='networkplugins',
            name='plugin',
        ),
        migrations.DeleteModel(
            name='RoomPermissions',
        ),
        migrations.RemoveField(
            model_name='roomplugins',
            name='net',
        ),
        migrations.DeleteModel(
            name='NetworkPlugins',
        ),
        migrations.DeleteModel(
            name='Plugins',
        ),
        migrations.DeleteModel(
            name='RoomPlugins',
        ),
    ]
