# Generated by Django 2.2.19 on 2021-04-07 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('ref', models.TextField(blank=True)),
                ('scripture', models.TextField(blank=True)),
                ('num_rounds', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.TextField(blank=True)),
                ('host', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripture_game.GameGames')),
            ],
        ),
        migrations.CreateModel(
            name='GameSolveAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('attempt', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripture_game.GameGames')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripture_game.GameUsers')),
            ],
        ),
        migrations.AddField(
            model_name='gamegames',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scripture_game.GameUsers'),
        ),
    ]
