book_table = (
    ("gen", "Genesis"),
    ("exo", "Exodus"),
    ("lev", "Leviticus"),
    ("num", "Numbers"),
    ("deu", "Deuteronomy"),
    ("jos", "Joshua"),
    ("jdg", "Judges"),
    ("rut", "Ruth"),
    ("1sa", "1 Samuel"),
    ("2sa", "2 Samuel"),
    ("1ki", "1 Kings"),
    ("2ki", "2 Kings"),
    ("1ch", "1 Chronicles"),
    ("2ch", "2 Chronicles"),
    ("ezr", "Ezra"),
    ("neh", "Nehemiah"),
    ("est", "Esther"),
    ("job", "Job"),
    ("psa", "Psalms"),
    ("pro", "Proverbs"),
    ("ecc", "Ecclesiastes"),
    ("son", "Songs of Solomon"),
    ("isa", "Isaiah"),
    ("jer", "Jeremiah"),
    ("lam", "Lamentations"),
    ("eze", "Ezekiel"),
    ("dan", "Daniel"),
    ("hos", "Hosea"),
    ("joe", "Joel"),
    ("amo", "Amos"),
    ("oba", "Obadiah"),
    ("jon", "Jonah"),
    ("mic", "Micah"),
    ("nah", "Nahum"),
    ("hab", "Habakkuk"),
    ("zep", "Zephaniah"),
    ("hag", "Haggai"),
    ("zec", "Zechariah"),
    ("mal", "Malachi"),
    ("mat", "Matthew"),
    ("mar", "Mark"),
    ("luk", "Luke"),
    ("joh", "John"),
    ("act", "Acts"),
    ("rom", "Romans"),
    ("1co", "1 Corinthians"),
    ("2co", "2 Corinthians"),
    ("gal", "Galatians"),
    ("eph", "Ephesians"),
    ("phi", "Philippians"),
    ("col", "Colossians"),
    ("1th", "1 Thessalonians"),
    ("2th", "2 Thessalonians"),
    ("1ti", "1 Timothy"),
    ("2ti", "2 Timothy"),
    ("tit", "Titus"),
    ("phl", "Philemon"),
    ("heb", "Hebrews"),
    ("jam", "James"),
    ("1pe", "1 Peter"),
    ("2pe", "2 Peter"),
    ("1jo", "1 John"),
    ("2jo", "2 John"),
    ("3jo", "3 John"),
    ("jud", "Jude"),
    ("rev", "Revelation"),
    )

    
xref_books = ['Gen', 'Exod', 'Lev', 'Num', 'Deut', 'Josh', 'Judg', 'Ruth', '1Sam', '2Sam', 
	'1Kgs', '2Kgs', '1Chr', '2Chr', 'Ezra', 'Neh', 'Esth', 'Job', 'Ps', 'Prov', 
	'Eccl', 'Song', 'Isa', 'Jer', 'Lam', 'Ezek', 'Dan', 'Hos', 'Joel', 'Amos', 'Obad', 
	'Jonah', 'Mic', 'Nah', 'Hab', 'Zeph', 'Hag', 'Zech', 'Mal', 'Matt', 'Mark', 'Luke', 
	'John', 'Acts', 'Rom', '1Cor', '2Cor', 'Gal', 'Eph', 'Phil', 'Col', '1Thess', 
	'2Thess', '1Tim', '2Tim', 'Titus', 'Phlm', 'Heb', 'Jas', '1Pet', '2Pet', '1John',
	'2John', '3John', 'Jude', 'Rev']