# Generated by Django 2.2.28 on 2025-03-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_manage', '0010_auto_20160825_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nickhistory',
            name='host_mask',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
